/**
 * Shipped starter PRICES, per unit of sale — GENERATED by
 * pricing/loadStarterSheets.mts from the owner's filled
 * pricing/starter-catalog-pricing.xlsx. Do not edit by hand: change the
 * sheet and run the loader (Track A only).
 *
 * Name -> price per unit of sale, as a decimal string ("0.4000"). A shipped
 * row not listed here ships unpriced ($0), as every row has until now.
 *
 * ── EMPTY until `materials.isExamplePrice` exists ────────────────────────────
 * A shipped price must say "Example price" on the shop's bid screen and warn
 * before printing (CLAUDE.md § "Where a priced catalog lands", owner
 * 2026-10-07). `server/starterValues.test.ts` fails if this map holds a
 * single price while the schema has no `isExamplePrice` column.
 */
export const STARTER_PRICES: Readonly<Record<string, string>> = {};
