/**
 * Shipped BRAND VARIANT prices (panels and breakers), per unit of sale —
 * GENERATED by pricing/loadStarterSheets.mts from the owner's filled
 * pricing/brand-variants-pricing.xlsx. Do not edit by hand.
 *
 * Variant name -> its generic parent and price. NOTHING READS THIS YET: the
 * app has no parent/variant model (`materials.parentId`, ASSEMBLIES_PLAN.md
 * § "Parent items and brand variants"). The prices are kept ready for it.
 *
 * ── EMPTY until the variant model AND the example tag exist ─────────────────
 * `server/starterValues.test.ts` fails if this map holds a price while the
 * schema has no `materials.parentId` or no `materials.isExamplePrice`.
 */
export const STARTER_BRAND_PRICES: Readonly<
  Record<string, { parent: string; price: string }>
> = {};
