/**
 * Shipped starter LABOR UNITS — GENERATED by pricing/loadStarterSheets.mts
 * from the owner's filled pricing/labor-units-starter.xlsx. Do not edit by
 * hand: change the sheet and run the loader (Track A only).
 *
 * Name -> hours in the column's own units: `laborHours` per EACH, or per FOOT
 * on a row sold by the foot (the sheet's "per 100 ft" divided by 100);
 * `fieldBendLaborHours` per bend, raceways only. A shipped row not listed
 * here ships with no hours (NULL — "not set", never 0).
 *
 * ── EMPTY until shipped hours can say they are an example ────────────────────
 * The same reason as starterPrices.ts: a number nobody at the shop chose must
 * not look like one they did. `server/starterValues.test.ts` fails if this
 * map holds an entry before a way to tag shipped hours exists (owner
 * question in references/starter-vs-company-plan.md § 3).
 */
export const STARTER_LABOR_UNITS: Readonly<
  Record<string, { laborHours?: string; fieldBendLaborHours?: string }>
> = {};
