/**
 * Shipped STEP TIMES — GENERATED by pricing/loadStarterSheets.mts from the
 * owner's "Steps" tab of pricing/starter-catalog-pricing.xlsx
 * (references/step-based-labor-plan.md § 14). Do not edit by hand: change the
 * sheet and run the loader (Track A only).
 *
 * Step key (server/seed/starterLaborSteps.ts) -> minutes for ONE count, as a
 * string. A key not listed ships with NO time (NULL — "not set", never 0).
 *
 * ── EMPTY until the owner types minutes ──────────────────────────────────────
 * So every shipped step total is NOT SET, typed starter hours keep pricing,
 * and no bid number moves (plan § 13a). A loaded time arrives with its
 * "Example hours" tag (`labor_steps.isExampleMinutes`).
 */
export const STARTER_STEP_MINUTES: Readonly<Record<string, string>> = {};
