/**
 * Shipped starter ASSEMBLY HOURS — GENERATED by pricing/loadStarterSheets.mts
 * from the owner's filled pricing/assembly-hours-starter.xlsx. Do not edit by
 * hand.
 *
 * Starter assembly name -> base labor hours for one installed. A starter not
 * listed keeps the hours its seed entry gives it (null = not set). The seed
 * applies a listed value at insert AND re-stamps it on shipped assemblies on
 * every start — only for the names listed here, so a starter nobody filled in
 * is never touched (server/db.ts, seedBaselineAssemblies).
 *
 * ── EMPTY until shipped hours can say "Example hours" ────────────────────────
 * Owner, 2026-10-07: shipped labor hours get the price treatment — an
 * "Example hours" tag on the bid screen (never the customer quote), cleared
 * when the shop edits it, a warning before printing. `server/starterValues
 * .test.ts` fails if this map holds a value while `assemblies.isExampleHours`
 * does not exist.
 */
export const STARTER_ASSEMBLY_HOURS: Readonly<Record<string, string>> = {};
