/**
 * Shipped starter OVERHEAD and the starters whose typed hours were CLEARED —
 * GENERATED by pricing/loadStarterSheets.mts from the owner's "Step totals"
 * tab (references/step-based-labor-plan.md § 13b, § 14). Do not edit by hand.
 *
 * `STARTER_ASSEMBLY_OVERHEAD`: starter name -> overhead hours (layout,
 * handling, cleanup — owner Q2), stamped on the SHARED row with its "Example
 * hours" tag.
 *
 * `STARTER_HOURS_CLEARED`: starters whose typed hours the loader cleared so
 * their steps price (owner Q7). The loader lists a name ONLY when
 * `starterHoursClearable` says yes — step total set, and step total +
 * overhead ≥ the current hours ("a little high beats low"). A seed test holds
 * this list to that rule.
 *
 * ── EMPTY until the owner fills the sheet ────────────────────────────────────
 * Nothing is stamped or cleared, so no bid number moves (plan § 13a).
 */
export const STARTER_ASSEMBLY_OVERHEAD: Readonly<Record<string, string>> = {};

export const STARTER_HOURS_CLEARED: readonly string[] = [];
