/**
 * Every catalog row a starter assembly uses, under a STABLE KEY.
 *
 * ── Why recipes say a key and never a name ───────────────────────────────────
 * A materials rename is coming (materials-naming-and-pricing-plan.md). The
 * seeder used to look parts up by the exact name typed in each recipe, so a
 * rename that missed one recipe line skipped that starter on every database
 * seeded afterwards, with only a console warning — "20/2 breaker" did exactly
 * that to "200A main panel furnish and install" until 2026-09-24.
 *
 * Now a recipe names a key from this table, and the table is the ONLY place a
 * starter mentions a catalog name. The key never changes: when "20A
 * Single-Pole breaker" becomes "20A 1-Pole breaker", the key stays
 * "20a-single-pole-breaker" and only the value moves. A typo in a key is a
 * compile error, not a skipped starter.
 *
 * ── Why a key and not the database id ────────────────────────────────────────
 * Material ids are assigned by each database, so a seed file cannot carry
 * one: the same row is a different id on a fresh database, the local copy
 * and production. At seed time the key resolves to the current name (through
 * RENAMED_BASELINE_MATERIALS, so a rename that edits the map and forgets this
 * table still resolves) and then to that database's id. Once seeded, an
 * assembly line points at the material by id (`assembly_materials.materialId`)
 * and an in-place rename never touches it.
 *
 * `server/starterAssembliesSeed.test.ts` fails if any value here stops naming
 * a shipped row.
 */
import { RENAMED_BASELINE_MATERIALS } from "../../shared/renamedMaterials";

export const STARTER_PARTS = {
  "0-10v-dimmer": "0-10V dimmer",
  "1-1-4in-flexible-metal-conduit": '1-1/4" flexible metal conduit',
  "1-1-4in-flexible-metal-conduit-connector":
    '1-1/4" flexible metal conduit connector',
  "1-2in-all-thread-rod-10-ft": '1/2" all-thread rod, 10 ft',
  "1-2in-cable-connector": '1/2" cable connector',
  "1-2in-conduit-locknut": '1/2" conduit locknut',
  "1-2in-emt-raintight-connector": '1/2" EMT raintight connector',
  "1-2in-flexible-metal-conduit": '1/2" flexible metal conduit',
  "1-2in-flexible-metal-conduit-connector":
    '1/2" flexible metal conduit connector',
  "1-2in-liquidtight-flexible-conduit": '1/2" liquidtight flexible conduit',
  "1-2in-liquidtight-flexible-conduit-connector":
    '1/2" liquidtight flexible conduit connector',
  "1-2in-weatherproof-box-double-gang": '1/2" weatherproof box, double-gang',
  "1-2in-weatherproof-box-single-gang": '1/2" weatherproof box, single-gang',
  "1-2in-weatherproof-round-box": '1/2" weatherproof round box',
  "1-gang-blank-plate": "1-gang blank plate",
  "10-2-mc-cable": "10/2 MC cable Copper",
  "10-2-nm-b": "10/2 NM-B Copper",
  "10-3-mc-cable": "10/3 MC cable Copper",
  "10-3-nm-b": "10/3 NM-B Copper",
  "100a-3-pole-breaker": "100A 3-Pole breaker",
  "100a-cartridge-fuse": "100A cartridge fuse",
  "100a-fused-disconnect-nema-1": "100A fused disconnect, NEMA 1",
  "100a-main-lug-sub-panel-24-space": "100A main-lug sub-panel, 24-space",
  "100a-meter-base": "100A meter base",
  "12-2-mc-cable": "12/2 MC cable Copper",
  "12-2-mc-cable-isolated-ground": "12/2 MC cable isolated ground Copper",
  "12-2-nm-b": "12/2 NM-B Copper",
  "12-2-submersible-pump-cable": "12/2 submersible pump cable Copper",
  "12-2-uf-b": "12/2 UF-B Copper",
  "12-3-mc-cable": "12/3 MC cable Copper",
  "12-3-nm-b": "12/3 NM-B Copper",
  "12x12-pull-box": "12x12 pull box",
  "14-2-fire-alarm-cable": "14/2 fire alarm cable Copper",
  "14-2-nm-b": "14/2 NM-B Copper",
  "14-3-nm-b": "14/3 NM-B Copper",
  "14-4-mini-split-cable": "14/4 mini-split cable Copper",
  "15a-single-pole-breaker": "15A 1-Pole breaker",
  "16-2-speaker-wire": "16/2 speaker wire Copper",
  "18-2-control-wire": "18/2 control wire Copper",
  "18-3-control-wire": "18/3 control wire Copper",
  "18-4-control-wire": "18/4 control wire Copper",
  "18-5-control-wire": "18/5 control wire Copper",
  "1in-cable-connector": '1" cable connector',
  "1x4-led-troffer": "1x4 LED troffer",
  "2-0-4-0-awg-crimp-lug": "2/0-4/0 AWG crimp lug",
  "2-gang-wall-plate": "2-gang wall plate",
  "200a-main-panel": "200A main panel",
  "200a-main-panel-40-space": "200A main panel, 40-space",
  "200a-meter-base": "200A meter base",
  "20a-2-pole-breaker": "20A 2-Pole breaker",
  "20a-2-pole-gfci-breaker": "20A 2-Pole GFCI breaker",
  "20a-3-way-switch": "20A 3-way switch",
  "20a-duplex-receptacle": "20A duplex receptacle",
  "20a-gfci-receptacle": "20A GFCI receptacle",
  "20a-gfci-receptacle-weather-resistant":
    "20A GFCI receptacle, weather-resistant",
  "20a-single-pole-afci-gfci-combo-breaker":
    "20A 1-Pole AFCI/GFCI combo breaker",
  "20a-single-pole-breaker": "20A 1-Pole breaker",
  "20a-single-pole-gfci-breaker": "20A 1-Pole GFCI breaker",
  "20a-single-pole-switch": "20A single-pole switch",
  "20a-single-receptacle": "20A single receptacle",
  "225a-panelboard-3-phase-main-42-space":
    "225A panelboard, 3-phase main, 42-space",
  "225a-panelboard-3-phase-main-lug-42-space":
    "225A panelboard, 3-phase main-lug, 42-space",
  "24in-under-cabinet-light-bar": '24" under-cabinet light bar',
  "2in-conduit-bushing": '2" conduit bushing',
  "2in-conduit-locknut": '2" conduit locknut',
  "2in-mast-roof-flashing": '2" mast roof flashing',
  "2in-metal-weatherhead": '2" metal weatherhead',
  "2in-meter-hub": '2" meter hub',
  "2in-rigid-conduit": '2" rigid conduit',
  "2in-rigid-conduit-coupling": '2" rigid conduit coupling',
  "2in-riser-strap": '2" riser strap',
  "2in-se-cable-connector": '2" SE cable connector',
  "2x2-led-troffer": "2x2 LED troffer",
  "2x4-led-troffer": "2x4 LED troffer",
  "3-4in-cable-connector": '3/4" cable connector',
  "3-4in-conduit-locknut": '3/4" conduit locknut',
  "3-4in-emt-raintight-connector": '3/4" EMT raintight connector',
  "3-4in-liquidtight-flexible-conduit": '3/4" liquidtight flexible conduit',
  "3-4in-liquidtight-flexible-conduit-connector":
    '3/4" liquidtight flexible conduit connector',
  "3-8in-all-thread-rod-10-ft": '3/8" all-thread rod, 10 ft',
  "3-8in-cable-connector": '3/8" cable connector',
  "3-8in-flat-washer": '3/8" flat washer',
  "3-8in-hex-nut": '3/8" hex nut',
  "3-8in-mc-connector": '3/8" MC connector',
  "3-gang-wall-plate": "3-gang wall plate",
  "3-way-dimmer": "3-way dimmer",
  "3-way-switch": "3-way switch",
  "300w-landscape-transformer": "300W landscape transformer",
  "30a-2-pole-breaker": "30A 2-Pole breaker",
  "30a-3-pole-breaker": "30A 3-Pole breaker",
  "30a-dryer-receptacle": "30A dryer receptacle",
  "30a-generator-cord": "30A generator cord",
  "30a-non-fused-disconnect-nema-1": "30A non-fused disconnect, NEMA 1",
  "30a-non-fused-disconnect-nema-3r": "30A non-fused disconnect, NEMA 3R",
  "30a-power-inlet-box": "30A power inlet box",
  "4-0-4-0-4-0-2-0-ser-al": "4/0-4/0-4/0-2/0 SER Aluminum",
  "4-11-16in-square-box": '4-11/16" square box',
  "4-11-16in-square-mud-ring-2-gang": '4-11/16" square mud ring, 2-gang',
  "4-ft-led-strip-fixture": "4 ft LED strip fixture",
  "4-ft-led-t8-tube-ballast-bypass": "4 ft LED T8 tube, ballast bypass",
  "4-ft-led-t8-tube-ballast-compatible": "4 ft LED T8 tube, ballast compatible",
  "4-ft-led-wraparound": "4 ft LED wraparound",
  "4-ft-vapor-tight-fixture": "4 ft vapor tight fixture",
  "4-way-switch": "4-way switch",
  "400a-panelboard-3-phase-main-42-space":
    "400A panelboard, 3-phase main, 42-space",
  "40a-2-pole-breaker": "40A 2-Pole breaker",
  "45-kva-dry-type-transformer-480v-208y-120v-3-phase":
    "45 kVA dry-type transformer, 480V-208Y/120V 3-phase",
  "48a-ev-charger": "48A EV charger",
  "4in-insulated-flex-duct": '4" insulated flex duct',
  "4in-led-retrofit-trim": '4" LED retrofit trim',
  "4in-recessed-can-new-construction-ic":
    '4" recessed can, new construction IC',
  "4in-roof-vent-cap": '4" roof vent cap',
  "4in-shower-wet-rated-trim": '4" shower wet-rated trim',
  "4in-square-blank-cover": '4" square blank cover',
  "4in-square-box": '4" square box',
  "4in-square-mud-ring": '4" square mud ring',
  "4in-square-mud-ring-2-gang": '4" square mud ring, 2-gang',
  "4in-square-mud-ring-fixture": '4" square mud ring, fixture',
  "4in-square-raised-cover-duplex": '4" square raised cover, duplex',
  "4in-wafer-led-downlight": '4" canless wafer LED downlight',
  "4in-wall-vent-cap": '4" wall vent cap',
  "50a-2-pole-breaker": "50A 2-Pole breaker",
  "50a-2-pole-gfci-breaker": "50A 2-Pole GFCI breaker",
  "50a-range-receptacle": "50A range receptacle",
  "50a-rv-receptacle": "50A RV receptacle",
  "5in-6in-led-retrofit-trim": '5"/6" LED retrofit trim',
  // The 5"/6" row, renamed in place to the 6" canless wafer (owner,
  // 2026-10-07). The key stays, so LT7's recipe is untouched.
  "5in-6in-wafer-led-downlight": '6" canless wafer LED downlight',
  "6-3-nm-b": "6/3 NM-B Copper",
  "60a-2-pole-breaker": "60A 2-Pole breaker",
  "60a-gfci-spa-disconnect": "60A GFCI spa disconnect",
  "60a-main-panel-8-space": "60A main panel, 8-space",
  "60a-non-fused-disconnect-nema-1": "60A non-fused disconnect, NEMA 1",
  "60a-non-fused-disconnect-nema-3r": "60A non-fused disconnect, NEMA 3R",
  "60a-non-fused-pullout-disconnect": "60A non-fused pullout disconnect",
  "6ft-mc-whip": "6 ft MC whip",
  "6in-recessed-can-new-construction-ic":
    '6" recessed can, new construction IC',
  "6in-recessed-can-remodel-ic": '6" recessed can, remodel IC',
  "6x6-pull-box": "6x6 pull box",
  "70a-3-pole-breaker": "70A 3-Pole breaker",
  "8-2-nm-b": "8/2 NM-B Copper",
  "8-ft-led-strip-fixture": "8 ft LED strip fixture",
  "8-ft-led-t8-tube-ballast-bypass-ho": "8 ft LED T8 tube, ballast bypass, HO",
  "8-ft-led-t8-tube-ballast-bypass-single-pin":
    "8 ft LED T8 tube, ballast bypass, single-pin",
  "8-ft-lighting-track": "8 ft lighting track",
  "8-ft-mc-whip": "8 ft MC whip",
  "ac-condenser-whip": "AC condenser whip",
  "afci-receptacle": "AFCI receptacle",
  "arc-flash-label": "Arc flash label",
  "attic-fan": "Attic fan",
  "attic-fan-thermostat": "Attic fan thermostat",
  "automatic-transfer-switch": "Automatic transfer switch",
  "baseboard-heater": "Baseboard heater",
  "baseboard-heater-thermostat": "Baseboard heater thermostat",
  "bath-exhaust-fan-80-cfm": "Bath exhaust fan, 80 CFM",
  "bath-exhaust-fan-light-combo": "Bath exhaust fan, light combo",
  "beam-clamp": "Beam clamp",
  "breaker-lock-off": "Breaker lock-off",
  "cat6-cable": "Cat6 cable Copper",
  "cat6-jack": "Cat6 jack",
  "cat6-patch-cord-3-ft": "Cat6 patch cord, 3 ft",
  "cat6-patch-panel": "Cat6 patch panel",
  "cat6-rj45-end": "Cat6 RJ45 end",
  "ceiling-fan": "Ceiling fan",
  "ceiling-fan-brace-box": "Ceiling fan brace box",
  "ceiling-occupancy-sensor-dual-tech": "Ceiling occupancy sensor, dual-tech",
  "ceiling-support-wire": "Ceiling support wire",
  chandelier: "Chandelier",
  "coax-f-connector": "Coax F connector",
  "coax-wall-plate": "Coax wall plate",
  "combination-fan-light-control": "Combination fan/light control",
  "combination-meter-main": "Combination meter-main",
  "concrete-wedge-anchor": "Concrete wedge anchor",
  "controlled-duplex-receptacle": "Controlled duplex receptacle",
  "cord-grip": "Cord grip",
  "detector-base": "Detector base",
  "detector-relay-module": "Detector relay module",
  dimmer: "Dimmer",
  "dishwasher-whip": "Dishwasher whip",
  "doorbell-button": "Doorbell button",
  "doorbell-chime-wired": "Doorbell chime, wired",
  "doorbell-transformer": "Doorbell transformer",
  "double-gang-box": "Double-gang box",
  "dryer-cord-4-wire": "Dryer cord, 4-wire",
  "dual-tech-occupancy-sensor-switch": "Dual-tech occupancy sensor switch",
  "duct-clamp": "Duct clamp",
  "duct-seal": "Duct seal",
  "duct-smoke-detector": "Duct smoke detector",
  "duplex-receptacle": "Duplex receptacle",
  "emergency-exit-light-combo": "Emergency exit light combo",
  "equipment-shut-off-relay": "Equipment shut-off relay",
  "exit-sign": "Exit sign",
  "fan-rated-ceiling-box": "Fan-rated ceiling box",
  "fire-alarm-horn-strobe": "Fire alarm horn/strobe",
  "fire-alarm-pull-station": "Fire alarm pull station",
  "firestop-caulk": "Firestop caulk",
  "fixture-mounting-bracket": "Fixture mounting bracket",
  "floor-box": "Floor box",
  "floor-box-cover": "Floor box cover",
  "furniture-feed-connector": "Furniture feed connector",
  "garbage-disposal-cord": "Garbage disposal cord",
  "generator-battery-charger": "Generator battery charger",
  "generator-interlock-kit": "Generator interlock kit",
  "generator-pad": "Generator pad",
  "gfci-receptacle": "GFCI receptacle",
  "gfci-receptacle-weather-resistant": "GFCI receptacle, weather-resistant",
  "grid-box-bracket": "Grid box bracket",
  "ground-bar-kit": "Ground bar kit",
  "ground-lug-compression": "Ground lug, compression",
  "ground-rod-8-ft": 'Ground rod, 5/8" x 8 ft',
  "ground-rod-clamp": "Ground rod clamp",
  "grounding-pigtail": "Grounding pigtail",
  "handy-box": "Handy box",
  "handy-box-cover-single-toggle": "Handy box cover, single toggle",
  "hardwired-smoke-co-detector": "Hardwired smoke/CO detector",
  "high-bay": "High bay",
  "hood-suppression-micro-switch": "Hood suppression micro-switch",
  "horizontal-cable-manager": "Horizontal cable manager",
  "humidity-sensor-switch": "Humidity sensor switch",
  "in-ceiling-speaker": "In-ceiling speaker",
  "independent-support-wire-clip": "Independent support wire clip",
  "intersystem-bonding-bridge": "Intersystem bonding bridge",
  "isolated-ground-receptacle": "Isolated-ground receptacle",
  "j-hook": "J-hook",
  "key-switch": "Key switch",
  "keystone-wall-plate-1-port": "Keystone wall plate, 1-port",
  "l14-30-receptacle": "L14-30 receptacle",
  "l5-20-receptacle": "L5-20 receptacle",
  "l6-30-receptacle": "L6-30 receptacle",
  "landscape-hub-connector": "Landscape hub connector",
  "landscape-light-fixture": "Landscape light fixture",
  "landscape-lighting-cable": "Landscape lighting cable Copper",
  "led-corn-bulb-e39": "LED corn bulb, E39",
  "led-par20-bulb": "LED PAR20 bulb",
  "led-pendant-fixture": "LED pendant fixture",
  "led-security-light-motion-activated-2-head":
    "LED security light, motion-activated, 2-head",
  "led-troffer-retrofit-kit": "LED troffer retrofit kit",
  "led-wall-sconce": "LED wall sconce",
  "lighting-contactor": "Lighting contactor",
  "low-voltage-mud-ring": "Low-voltage mud ring",
  "mc-anti-short-bushing": "MC anti-short bushing",
  "modular-furniture-whip-6-ft": "Modular furniture whip, 6 ft",
  "motor-rated-toggle-switch": "Motor-rated toggle switch",
  "motor-starter-size-1": "Motor starter, size 1",
  "network-rack-wall-mount": "Network rack, wall mount",
  "no10-thhn": "#10 THHN Copper",
  "no12-thhn": "#12 THHN Copper",
  "no14-thhn": "#14 THHN Copper",
  "no2-0-xhhw-al": "2/0 XHHW Aluminum",
  "no4-0-xhhw-al": "4/0 XHHW Aluminum",
  "no4-bare-cu-stranded": "#4 bare stranded Copper",
  "no6-bare-cu-stranded": "#6 bare stranded Copper",
  "no6-thhn": "#6 THHN Copper",
  "no8-bare-cu-solid": "#8 bare solid Copper",
  "no8-thhn": "#8 THHN Copper",
  "non-shunted-lampholder": "Non-shunted lampholder",
  "octagon-box-metal": "Octagon box, metal",
  "octagon-box-plastic": "Octagon box, plastic",
  "panel-directory-label": "Panel directory label",
  "panel-filler-plate": "Panel filler plate",
  "panel-knockout-seal": "Panel knockout seal",
  photocell: "Photocell",
  "poke-through-device-2-service": "Poke-through device, 2-service",
  "power-pole-fitting-kit": "Power pole fitting kit",
  "quad-receptacle": "Quad receptacle",
  "range-cord-4-wire": "Range cord, 4-wire",
  "range-hood-fan": "Range hood fan",
  "rapid-entry-key-box": "Rapid-entry key box",
  "rg6-coax-cable": "RG6 coax cable Copper",
  "roof-flashing-boot": "Roof flashing boot",
  "security-camera-dome": "Security camera, dome",
  "sensor-power-pack-120-277v": "Sensor power pack, 120/277V",
  "shallow-round-box": "Shallow round box",
  "shunt-trip-breaker-2-pole": "Shunt-trip breaker, 2-Pole",
  "siding-mounting-block": "Siding mounting block",
  "silicone-sealant": "Silicone sealant",
  "single-gang-box": "Single-gang box",
  "single-gang-old-work-box": "Single-gang old-work box",
  "single-pole-switch": "Single-pole switch",
  "spa-bonding-lug": "Spa bonding lug",
  "structured-media-enclosure": "Structured media enclosure",
  "submersible-pump-splice-kit": "Submersible pump splice kit",
  "surface-mount-ceiling-fixture": "Surface-mount ceiling fixture",
  "surge-protective-device": "Surge protective device",
  "switch-receptacle-combo-device": "Switch/receptacle combo device",
  "system-smoke-detector": "System smoke detector",
  "t-bar-grid-clip": "T-bar grid clip",
  "tele-power-pole-10-ft": "Tele-power pole, 10 ft",
  "temporary-light-string-100-ft": "Temporary light string, 100 ft",
  "temporary-pole-6x6-post": "Temporary pole, 6x6 post",
  "time-clock": "Time clock",
  "timer-switch": "Timer switch",
  "track-light-end-feed": "Track light end feed",
  "track-light-head": "Track light head",
  "trapeze-hanger-kit": "Trapeze hanger kit",
  "triple-gang-box": "Triple-gang box",
  "unit-heater": "Unit heater",
  "usb-combo-receptacle": "USB combo receptacle",
  "vanity-light-3-light": "Vanity light, 3-light",
  "variable-frequency-drive": "Variable frequency drive",
  "video-doorbell": "Video doorbell",
  "video-doorbell-chime-kit": "Video doorbell chime kit",
  "wall-pack-full-cutoff": "Wall pack, full cutoff",
  "wall-plate": "Wall plate",
  "water-pipe-bonding-clamp": "Water pipe bonding clamp",
  "weatherproof-in-use-cover": "Weatherproof in-use cover",
  "weatherproof-in-use-cover-2-gang": "Weatherproof in-use cover, 2-gang",
  "well-pump-control-box": "Well pump control box",
  "well-pump-pressure-switch": "Well pump pressure switch",
  "whole-house-surge-protector": "Whole-house surge protector",
  "wire-nuts": "Wire nuts",
} as const satisfies Record<string, string>;

export type StarterPart = keyof typeof STARTER_PARTS;

/**
 * The catalog name a part goes by NOW: the table's value, followed through
 * the rename map in case a rename updated the map but not this table.
 */
export function starterPartName(part: StarterPart): string {
  let name: string = STARTER_PARTS[part];
  // The map points straight at final names; the bound only guards a cycle.
  for (let hop = 0; hop < 5 && name in RENAMED_BASELINE_MATERIALS; hop++) {
    name = RENAMED_BASELINE_MATERIALS[name];
  }
  return name;
}
