/**
 * The catalog names FROZEN from the owner-marked materials review sheet,
 * 2026-10-07 — GENERATED from pricing/frozen-names.json (do not edit by
 * hand; re-run the read-back, pricing/readMaterialsReview.mts, and regenerate).
 *
 * Each pair is a shipped row renamed IN PLACE: shared/renamedMaterials.ts
 * adds every pair to RENAMED_BASELINE_MATERIALS and points every older
 * spelling straight at the final name, so no database depends on the rename
 * pass walking a chain. server/frozenMaterialNames.test.ts checks the seed
 * files ship exactly these names.
 */
export const FROZEN_RENAMES_2026_10_07: readonly {
  current: string;
  final: string;
}[] = [
  { current: "#14 bare CU, solid", final: "#14 bare solid Copper" },
  { current: "#12 bare CU, solid", final: "#12 bare solid Copper" },
  { current: "#10 bare CU, solid", final: "#10 bare solid Copper" },
  { current: "#8 bare CU, solid", final: "#8 bare solid Copper" },
  { current: "#10 bare CU, stranded", final: "#10 bare stranded Copper" },
  { current: "#8 bare CU, stranded", final: "#8 bare stranded Copper" },
  { current: "#6 bare CU, stranded", final: "#6 bare stranded Copper" },
  { current: "#4 bare CU, stranded", final: "#4 bare stranded Copper" },
  { current: "#2 bare CU, stranded", final: "#2 bare stranded Copper" },
  { current: "#1/0 bare CU, stranded", final: "1/0 bare stranded Copper" },
  { current: "#2/0 bare CU, stranded", final: "2/0 bare stranded Copper" },
  { current: "16-2 fire alarm cable", final: "16/2 fire alarm cable Copper" },
  { current: "14-2 fire alarm cable", final: "14/2 fire alarm cable Copper" },
  { current: "#18 fixture wire", final: "#18 fixture wire Copper" },
  { current: "#16 fixture wire", final: "#16 fixture wire Copper" },
  { current: "14-2 MC cable", final: "14/2 MC cable Copper" },
  { current: "14-3 MC cable", final: "14/3 MC cable Copper" },
  { current: "14-4 MC cable", final: "14/4 MC cable Copper" },
  { current: "12-2 MC cable", final: "12/2 MC cable Copper" },
  { current: "12-3 MC cable", final: "12/3 MC cable Copper" },
  { current: "12-4 MC cable", final: "12/4 MC cable Copper" },
  { current: "10-2 MC cable", final: "10/2 MC cable Copper" },
  { current: "10-3 MC cable", final: "10/3 MC cable Copper" },
  { current: "10-4 MC cable", final: "10/4 MC cable Copper" },
  { current: "8-2 MC cable", final: "8/2 MC cable Copper" },
  { current: "8-3 MC cable", final: "8/3 MC cable Copper" },
  { current: "8-4 MC cable", final: "8/4 MC cable Copper" },
  { current: "6-2 MC cable", final: "6/2 MC cable Copper" },
  { current: "6-3 MC cable", final: "6/3 MC cable Copper" },
  { current: "6-4 MC cable", final: "6/4 MC cable Copper" },
  { current: "4-2 MC cable", final: "4/2 MC cable Copper" },
  { current: "4-3 MC cable", final: "4/3 MC cable Copper" },
  { current: "3-3 MC cable", final: "3/3 MC cable Copper" },
  { current: "3-4 MC cable", final: "#3/4 MC cable Copper" },
  { current: "2-2 MC cable", final: "2/2 MC cable Copper" },
  { current: "2-3 MC cable", final: "2/3 MC cable Copper" },
  {
    current: "12-2 MC cable, isolated ground",
    final: "12/2 MC cable isolated ground Copper",
  },
  { current: "14-4 mini-split cable", final: "14/4 mini-split cable Copper" },
  { current: "14-2 NM-B", final: "14/2 NM-B Copper" },
  { current: "14-3 NM-B", final: "14/3 NM-B Copper" },
  { current: "12-2 NM-B", final: "12/2 NM-B Copper" },
  { current: "12-3 NM-B", final: "12/3 NM-B Copper" },
  { current: "10-2 NM-B", final: "10/2 NM-B Copper" },
  { current: "10-3 NM-B", final: "10/3 NM-B Copper" },
  { current: "8-2 NM-B", final: "8/2 NM-B Copper" },
  { current: "8-3 NM-B", final: "8/3 NM-B Copper" },
  { current: "6-3 NM-B", final: "6/3 NM-B Copper" },
  { current: "4-4-4-6 SER AL", final: "4-4-4-6 SER Aluminum" },
  { current: "2-2-2-4 SER AL", final: "2-2-2-4 SER Aluminum" },
  { current: "1/0-1/0-1/0-2 SER AL", final: "1/0-1/0-1/0-2 SER Aluminum" },
  { current: "2/0-2/0-2/0-1 SER AL", final: "2/0-2/0-2/0-1 SER Aluminum" },
  { current: "3/0-3/0-3/0-1/0 SER AL", final: "3/0-3/0-3/0-1/0 SER Aluminum" },
  { current: "4/0-4/0-2/0 SER AL", final: "4/0-4/0-2/0 SER Aluminum" },
  { current: "4/0-4/0-4/0-2/0 SER AL", final: "4/0-4/0-4/0-2/0 SER Aluminum" },
  { current: "250-250-250 SER AL", final: "250-250-250 SER Aluminum" },
  { current: "8-8-8-8 SER CU", final: "8-8-8-8 SER Copper" },
  { current: "6-6-6-6 SER CU", final: "6-6-6-6 SER Copper" },
  { current: "4-4-4-6 SER CU", final: "4-4-4-6 SER Copper" },
  { current: "2-2-2-4 SER CU", final: "2-2-2-4 SER Copper" },
  { current: "1-1-1-3 SER CU", final: "1-1-1-3 SER Copper" },
  { current: "4-4-6 SEU AL", final: "4-4-6 SEU Aluminum" },
  { current: "2-2-4 SEU AL", final: "2-2-4 SEU Aluminum" },
  { current: "14-3 SJOOW cord", final: "14/3 SJOOW cord Copper" },
  { current: "12-3 SOOW cord", final: "12/3 SOOW cord Copper" },
  { current: "10-3 SOOW cord", final: "10/3 SOOW cord Copper" },
  {
    current: "12-2 submersible pump cable",
    final: "12/2 submersible pump cable Copper",
  },
  { current: "#14 THHN", final: "#14 THHN Copper" },
  { current: "#12 THHN", final: "#12 THHN Copper" },
  { current: "#10 THHN", final: "#10 THHN Copper" },
  { current: "#8 THHN", final: "#8 THHN Copper" },
  { current: "#6 THHN", final: "#6 THHN Copper" },
  { current: "#4 THHN", final: "#4 THHN Copper" },
  { current: "#3 THHN", final: "#3 THHN Copper" },
  { current: "#2 THHN", final: "#2 THHN Copper" },
  { current: "#1 THHN", final: "#1 THHN Copper" },
  { current: "#1/0 THHN", final: "1/0 THHN Copper" },
  { current: "#2/0 THHN", final: "2/0 THHN Copper" },
  { current: "#3/0 THHN", final: "3/0 THHN Copper" },
  { current: "#4/0 THHN", final: "4/0 THHN Copper" },
  { current: "250 kcmil THHN", final: "250 kcmil THHN Copper" },
  { current: "300 kcmil THHN", final: "300 kcmil THHN Copper" },
  { current: "350 kcmil THHN", final: "350 kcmil THHN Copper" },
  { current: "400 kcmil THHN", final: "400 kcmil THHN Copper" },
  { current: "500 kcmil THHN", final: "500 kcmil THHN Copper" },
  { current: "#14 THHN stranded", final: "#14 THHN stranded Copper" },
  { current: "#12 THHN stranded", final: "#12 THHN stranded Copper" },
  { current: "#10 THHN stranded", final: "#10 THHN stranded Copper" },
  { current: "12-3 tray cable", final: "12/3 tray cable Copper" },
  { current: "14-2 UF-B", final: "14/2 UF-B Copper" },
  { current: "12-2 UF-B", final: "12/2 UF-B Copper" },
  { current: "10-2 UF-B", final: "10/2 UF-B Copper" },
  { current: "8-2 UF-B", final: "8/2 UF-B Copper" },
  { current: "1/0 URD triplex AL", final: "1/0 URD triplex Aluminum" },
  { current: "#4/0 USE-2 AL", final: "4/0 USE-2 Aluminum" },
  { current: "#8 XHHW AL", final: "#8 XHHW Aluminum" },
  { current: "#6 XHHW AL", final: "#6 XHHW Aluminum" },
  { current: "#4 XHHW AL", final: "#4 XHHW Aluminum" },
  { current: "#2 XHHW AL", final: "#2 XHHW Aluminum" },
  { current: "#1 XHHW AL", final: "#1 XHHW Aluminum" },
  { current: "#1/0 XHHW AL", final: "1/0 XHHW Aluminum" },
  { current: "#2/0 XHHW AL", final: "2/0 XHHW Aluminum" },
  { current: "#3/0 XHHW AL", final: "3/0 XHHW Aluminum" },
  { current: "#4/0 XHHW AL", final: "4/0 XHHW Aluminum" },
  { current: "250 kcmil XHHW AL", final: "250 kcmil XHHW Aluminum" },
  { current: "300 kcmil XHHW AL", final: "300 kcmil XHHW Aluminum" },
  { current: "350 kcmil XHHW AL", final: "350 kcmil XHHW Aluminum" },
  { current: "400 kcmil XHHW AL", final: "400 kcmil XHHW Aluminum" },
  { current: "500 kcmil XHHW AL", final: "500 kcmil XHHW Aluminum" },
  {
    current: "15A Single-Pole half-size breaker",
    final: "15A 1-Pole half-size breaker",
  },
  {
    current: "20A Single-Pole half-size breaker",
    final: "20A 1-Pole half-size breaker",
  },
  {
    current: "30A Single-Pole half-size breaker",
    final: "30A 1-Pole half-size breaker",
  },
  { current: "15A Single-Pole breaker", final: "15A 1-Pole breaker" },
  { current: "20A Single-Pole breaker", final: "20A 1-Pole breaker" },
  { current: "25A Single-Pole breaker", final: "25A 1-Pole breaker" },
  { current: "30A Single-Pole breaker", final: "30A 1-Pole breaker" },
  { current: "35A Single-Pole breaker", final: "35A 1-Pole breaker" },
  { current: "40A Single-Pole breaker", final: "40A 1-Pole breaker" },
  { current: "45A Single-Pole breaker", final: "45A 1-Pole breaker" },
  { current: "50A Single-Pole breaker", final: "50A 1-Pole breaker" },
  { current: "15A Single-Pole AFCI breaker", final: "15A 1-Pole AFCI breaker" },
  { current: "20A Single-Pole AFCI breaker", final: "20A 1-Pole AFCI breaker" },
  { current: "25A Single-Pole AFCI breaker", final: "25A 1-Pole AFCI breaker" },
  { current: "30A Single-Pole AFCI breaker", final: "30A 1-Pole AFCI breaker" },
  { current: "15A Single-Pole GFCI breaker", final: "15A 1-Pole GFCI breaker" },
  { current: "20A Single-Pole GFCI breaker", final: "20A 1-Pole GFCI breaker" },
  { current: "30A Single-Pole GFCI breaker", final: "30A 1-Pole GFCI breaker" },
  {
    current: "15A Single-Pole AFCI/GFCI combo breaker",
    final: "15A 1-Pole AFCI/GFCI combo breaker",
  },
  {
    current: "20A Single-Pole AFCI/GFCI combo breaker",
    final: "20A 1-Pole AFCI/GFCI combo breaker",
  },
  { current: "6ft MC whip", final: "6 ft MC whip" },
  {
    current: '4" wafer LED downlight',
    final: '4" canless wafer LED downlight',
  },
  {
    current: '5"/6" wafer LED downlight',
    final: '6" canless wafer LED downlight',
  },
  { current: "Ground rod, 8 ft", final: 'Ground rod, 5/8" x 8 ft' },
  { current: "Ground rod, 10 ft", final: 'Ground rod, 5/8" x 10 ft' },
  { current: "Cat5e cable", final: "Cat5e cable Copper" },
  { current: "Cat6 cable", final: "Cat6 cable Copper" },
  { current: "Cat6 shielded cable", final: "Cat6 shielded cable Copper" },
  { current: "Cat6A cable", final: "Cat6A cable Copper" },
  { current: "18/2 control wire", final: "18/2 control wire Copper" },
  { current: "18/3 control wire", final: "18/3 control wire Copper" },
  { current: "18/4 control wire", final: "18/4 control wire Copper" },
  { current: "18/5 control wire", final: "18/5 control wire Copper" },
  { current: "18/8 control wire", final: "18/8 control wire Copper" },
  {
    current: "Landscape lighting cable",
    final: "Landscape lighting cable Copper",
  },
  { current: "RG11 coax cable", final: "RG11 coax cable Copper" },
  { current: "RG6 coax cable", final: "RG6 coax cable Copper" },
  { current: "22/2 security cable", final: "22/2 security cable Copper" },
  { current: "22/4 security cable", final: "22/4 security cable Copper" },
  { current: "Security camera cable", final: "Security camera cable Copper" },
  { current: "16/2 speaker wire", final: "16/2 speaker wire Copper" },
  { current: "14/2 speaker wire", final: "14/2 speaker wire Copper" },
  { current: "#4/0 crimp sleeve", final: "4/0 crimp sleeve" },
];
