/**
 * Every countable symbol in the legends of the three reader-accuracy plan
 * sets, by the name to give its count AND its capture.
 *
 * ── Read off the sheets by eye, 2026-09-30 ───────────────────────────────────
 * Weld 1 p1 (E-001, "Electrical Symbols List" + "Telecom Symbols List"),
 * UNCC p1 (E001, "Electrical Symbol Schedule") and Old Blueridge p1 (E0.01,
 * "Symbol Schedule for Electrical Plan Drawings"). These are the legends the
 * four hand-count sheets (Weld 1 E-200, UNCC E111, Blueridge E1.01 and E1.02)
 * refer to, so this is a superset of what is drawn on those sheets: every
 * entry is here whether or not it appears, because an extra assembly costs
 * nothing and a missing one stops the count.
 *
 * Left out on purpose: abbreviations (TYP, UON, (E), WP …), wiring-line and
 * conduit conventions, homerun and feeder notation, room tags (ER, TR),
 * callouts (SDX), shading conventions for emergency/standby power, and UNCC's
 * "OS" room requirement, which its own legend says shows no device.
 *
 * ── The names ────────────────────────────────────────────────────────────────
 * Weld 1 and Blueridge: the legend's own words, as printed. UNCC writes a
 * paragraph per entry, so its names are the entry's own leading words,
 * shortened only where two entries would otherwise share a name. The test
 * pairs a count with the legend by name (case and spacing ignored), so the
 * name typed when CAPTURING a symbol must be this one too.
 */

export type LegendEntry = {
  name: string;
  /** Only where the assembly is filed in the library. */
  category:
    | "Devices"
    | "Lighting"
    | "Panels"
    | "Equipment Connections"
    | "Low Voltage/EMS";
};

const D = (name: string): LegendEntry => ({ name, category: "Devices" });
const L = (name: string): LegendEntry => ({ name, category: "Lighting" });
const P = (name: string): LegendEntry => ({ name, category: "Panels" });
const E = (name: string): LegendEntry => ({
  name,
  category: "Equipment Connections",
});
const V = (name: string): LegendEntry => ({
  name,
  category: "Low Voltage/EMS",
});

export const READER_TEST_LEGENDS: Record<string, LegendEntry[]> = {
  "Weld 1": [
    // Electrical symbols list, left column
    L("RECESSED MOUNTED LINEAR"),
    L("SURFACE MOUNTED LINEAR"),
    L("FLANGED MOUNTED LINEAR"),
    L("SUSPENDED MOUNTED LINEAR"),
    L("LINEAR STRIP"),
    L("WALL MOUNTED LINEAR"),
    L("WALL BRACKET"),
    L("OPEN DOWNLIGHT, SURFACE OR RECESSED"),
    L("RECESSED ADJUSTABLE DOWNLIGHT"),
    L("POLE MOUNTED LIGHT"),
    L("TRACK AND TRACK HEAD"),
    L("DECORATIVE FIXTURE"),
    D("LIGHTING CONTROL STATION"),
    L("EXIT SIGN, SINGLE FACE, CHEVRONS AS INDICATED"),
    L("EXIT SIGN, DUAL FACE, CHEVRONS AS INDICATED"),
    L(
      "EXIT SIGN, SINGLE FACE, CHEVRONS AS INDICATED, INTEGRAL EMERGENCY LIGHT"
    ),
    L("EXIT SIGN, LOW-LEVEL"),
    L("TWIN-HEAD EMERGENCY LIGHT"),
    P("PANELBOARD, FLUSH MOUNT"),
    P("PANELBOARD, SURFACE MOUNT"),
    D("POWER/TELECOM RISER"),
    // Electrical symbols list, right column
    D("SWITCH, SINGLE POLE"),
    D("SWITCH, THREE POLE"),
    D("DIMMER SWITCH, SINGLE POLE"),
    D("DIMMER SWITCH, THREE POLE"),
    D("SWITCH, MANUAL MOTOR STARTER"),
    D("OCCUPANCY SWITCH, SINGLE POLE, DUAL-TECHNOLOGY, UON"),
    D("CEILING MOUNTED OCCUPANCY SWITCH, SINGLE POLE, DUAL-TECHNOLOGY, UON"),
    D("CEILING MOUNTED DAYLIGHT SENSOR, 0-10V UON"),
    D("CONTROL STATION"),
    D("JUNCTION BOX"),
    D("DUPLEX RECEPTACLE"),
    D("DOUBLE DUPLEX RECEPTACLE"),
    D("DUPLEX RECEPTACLE, GFCI"),
    D("DUPLEX RECEPTACLE, HALF-SWITCHED"),
    D("DUPLEX RECEPTACLE, ISOLATED GROUND"),
    D("SPECIALTY RECEPTACLE (NEMA/IEC)"),
    D("DUPLEX RECEPTACLE - CEILING MOUNTED"),
    D("FLUSH FLOOR DUPLEX RECEPTACLE"),
    D("RECESSED CLOCK RECEPTACLE"),
    L("ILLUMINATED SIGNAGE"),
    E("COMBINATION DISCONNECT/MOTOR STARTER, 30 AMP, SIZE '1' UON"),
    E("DISCONNECT SWITCH, NON-FUSED, HEAVY-DUTY, 30 AMP, UON"),
    E("DISCONNECT SWITCH, FUSED, HEAVY DUTY, 30 AMP, UON"),
    E("CONTACTOR"),
    D("PHOTOCELL"),
    E("VARIABLE FREQUENCY DRIVE"),
    P("DISTRIBUTION TRANSFORMER"),
    // Telecom symbols list (E-200 carries a small security plan)
    V("TELECOM OUTLET"),
    V("TELECOM OUTLET COMPLETE WITH CABLING/JACKS"),
    V("FLUSH FLOOR TELECOM OUTLET"),
    V("TELECOM RACK, 2-POST, 45U, UON"),
    V("TELECOM RACK, 4-POST, 45U, UON"),
    V("TELECOM CABINET, FLUSH MOUNT"),
    V("TELECOM CABINET, SURFACE MOUNT"),
    V('A/V SYSTEM INTERFACE TOUCHPAD, +48" AFF UON'),
    V("CLOCK OUTLET"),
    V("WALL MOUNT PUBLIC ADDRESS SYSTEM SPEAKER"),
    V("CEILING MOUNT SPEAKER"),
    V("WALL MOUNT SPEAKER"),
    V("WIRELESS ACCESS POINT"),
    V("CCTV SYSTEM CAMERA"),
    V("VOLUME CONTROL STATION"),
    V("A/V SYSTEM SCREEN OUTLET"),
    V("MICROPHONE INPUT JACK"),
    V("PLYWOOD MOUNTING BACKBOARD"),
    V('CARD READER, +48" AFF UON'),
    V("WALL MOUNT BELL"),
    V("INTERCOM"),
  ],

  UNCC: [
    // Left column
    D("JUNCTION OR PULL BOX"),
    D("POWER OUTLET BOX FOR MOTORIZED PROJECTION SCREEN"),
    D("CONTROL SWITCH FOR MOTORIZED PROJECTION SCREEN"),
    D("POWER OUTLET BOX FOR MOTORIZED WINDOW SHADES"),
    D("CONTROL SWITCH FOR MOTORIZED WINDOW SHADES"),
    D("POWER OUTLET BOX FOR OVERHEAD PROJECTOR"),
    D("POWER WALL OUTLET BOX FOR AUTOMATIC PAPER TOWEL DISPENSER"),
    D("POWER WALL OUTLET BOX FOR ELECTRIC HAND DRYER"),
    L("LIGHTING FIXTURE, LINEAR TYPE"),
    L("LIGHTING FIXTURE, CEILING-MOUNTED POINT TYPE"),
    L("LIGHTING FIXTURE, WALL-MOUNTED POINT TYPE"),
    L("BOLLARD LIGHT OR POST-TOP AREA LIGHTING FIXTURE"),
    L("DIRECTIONAL LIGHTING FIXTURE"),
    L("EXIT SIGN, CEILING-MOUNTED, SINGLE FACE"),
    L("EXIT SIGN, CEILING-MOUNTED, DOUBLE FACE"),
    L("EXIT SIGN, WALL-MOUNTED, SINGLE FACE"),
    L("EXIT SIGN, END WALL-MOUNTED, SINGLE FACE"),
    L("EXIT SIGN, END WALL-MOUNTED, DOUBLE FACE"),
    D("DAYLIGHT SENSOR, WALL OR CEILING MOUNTED"),
    D("PHOTOELECTRIC SWITCH FOR LIGHTING CONTROL SYSTEM"),
    D("SINGLE POLE SWITCH"),
    D("DOUBLE POLE SWITCH"),
    D("THREE WAY SWITCH"),
    D("FOUR WAY SWITCH"),
    D("SWITCH WITH PILOT LIGHT"),
    D("LOW VOLTAGE SWITCH"),
    D("DIMMER SWITCH"),
    D("WALL BOX MOUNTED OCCUPANCY SENSOR/SWITCH"),
    E("AUTOMATIC GENERATOR TRANSFER DEVICE"),
    D('CONVENIENCE RECEPTACLE, 18" AFF'),
    D('CONVENIENCE RECEPTACLE, 48" AFF'),
    D("DOUBLE DUPLEX (QUAD) CONVENIENCE RECEPTACLE"),
    D("DUPLEX RECEPTACLE ON EMERGENCY CIRCUIT"),
    D("GFCI RECEPTACLE"),
    D("QUAD RECEPTACLE FOR ELECTRIC WATER COOLER"),
    D("WEATHER-RESISTANT GFCI RECEPTACLE"),
    D("CONVENIENCE RECEPTACLE, FLUSH IN CEILING"),
    D("DUPLEX RECEPTACLE FOR WALL MOUNTED TELEVISION"),
    D("USB DUPLEX CONVENIENCE OUTLET"),
    D("SPECIAL CONFIGURATION OUTLET"),
    V("COMBINATION DATA/TELEPHONE OUTLET"),
    V('TYPICAL TELECOM OUTLET, 48" AFF'),
    V("TELECOM OUTLET MOUNTED IN FURNITURE"),
    V("WALL TELEPHONE OUTLET"),
    V("DATA OUTLET FOR WALL MOUNTED TELEVISION"),
    D("WALL OUTLET BOX AND POWER CONNECTION TO OFFICE CUBICLE"),
    V("WALL OUTLET BOX AND TELECOM CONNECTION TO OFFICE CUBICLE"),
    V("CEILING-MOUNTED WIRELESS ACCESS POINT"),
    // Right column
    P("BRANCH CIRCUIT OR DISTRIBUTION PANELBOARD"),
    P("SURGE PROTECTOR (TVSS)"),
    P("DRY TYPE TRANSFORMER - THREE PHASE, 480-120/208 VOLTS"),
    P("DRY TYPE TRANSFORMER - THREE PHASE, 480-120/240 VOLTS"),
    P("DRY TYPE TRANSFORMER - SINGLE PHASE, 480-120/240 VOLTS"),
    E("115 OR 230 VOLT, 1 PHASE MOTOR"),
    E("208 OR 230 VOLT, 3 PHASE MOTOR"),
    E("460 VOLT, 3 PHASE MOTOR"),
    E("NONFUSIBLE DISCONNECT SWITCH"),
    E("FUSIBLE DISCONNECT SWITCH"),
    E("ENCLOSED CIRCUIT BREAKER"),
    E("MAGNETIC STARTER"),
    E("VFD TYPE MOTOR CONTROLLER"),
    E("COMBINATION MAGNETIC STARTER WITH NONFUSIBLE DISCONNECT"),
    E("MANUAL MOTOR STARTER"),
    P("GROUND ROD"),
    P("GROUNDING ELECTRODE SYSTEM"),
    P("MAIN POWER GROUND BAR"),
    V("TELECOMMUNICATIONS MAIN GROUND BAR"),
    V("TELECOMMUNICATIONS GROUND BAR"),
    E("MOTOR OPERATED ROLL-UP DOOR OR GATE"),
    V("RESCUE ASSISTANCE INTERCOM"),
    V("RESCUE ASSISTANCE MASTER"),
    V("GENERATOR REMOTE ANNUNCIATOR"),
    E("INSTANTANEOUS ELECTRIC WATER HEATER"),
    V("CEILING MOUNTED SURVEILLANCE TV CAMERA"),
    V("WALL MOUNTED SURVEILLANCE TV CAMERA"),
    V("SECURITY EQUIPMENT RACK"),
    V("DOOR RELEASE STATION"),
    V("INTERCOM STATION"),
    V("DURESS ALARM BUTTON"),
    V("CARD READER"),
    V("FIRE ALARM CONTROL PANEL"),
    V("FIRE ALARM ANNUNCIATOR PANEL"),
    V("DIGITAL FIRE ALARM TRANSMITTER"),
    V("FIRE ALARM TERMINAL WIRING CABINET"),
    V("FIRE ALARM MANUAL STATION"),
    V("CEILING MOUNTED SMOKE DETECTOR"),
    V("DUCT SMOKE DETECTOR"),
    V("FIRE ALARM BEAM TYPE SMOKE DETECTOR"),
    V("SPRINKLER ALARM-FLOW SWITCH"),
    V("SPRINKLER ALARM-TAMPER SWITCH"),
    V("CEILING MOUNTED HEAT DETECTOR"),
    V("WALL-MOUNTED FIRE ALARM SPEAKER/STROBE"),
    V("CEILING-MOUNTED FIRE ALARM SPEAKER/STROBE"),
    V("WALL MOUNTED FIRE ALARM STROBE LIGHT"),
    V("CEILING MOUNTED FIRE ALARM STROBE LIGHT"),
    V("KNOX BOX WITH SUPERVISORY SWITCH"),
    V("REMOTE ALARM INDICATING LIGHTS AND KEY TEST SWITCHES"),
    V("FIRE ALARM SYSTEM ZONE INTERFACE RELAY MODULE"),
    V("JUNCTION BOX FOR DOOR HOLDER"),
    D("HANDICAP DOOR OPERATOR PUSHBUTTON"),
    D("2-GANG POWER/DATA OUTLET FOR WALL-MOUNTED TELEVISION"),
    D("UNDERCARPET FLOOR POWER OUTLET"),
    D("UNDERCARPET FLOOR POWER AND DATA OUTLET"),
  ],

  "Old Blueridge school": [
    P("PANELBOARD - WALL MOUNTED"),
    E("MOTOR"),
    D("MOTOR RATED SNAP SWITCH"),
    D("SWITCH WITH TIMER"),
    L("ROUND FIXTURE - CEILING MOUNTED"),
    L("LINEAR FIXTURE - CEILING MOUNTED"),
    L("EXIT LIGHT FIXTURE"),
    D("LIGHTING SWITCH - WALL MOUNTED"),
    D("OCCUPANCY & DAYLIGHT SENSOR, CEILING MOUNTED"),
    D("DUPLEX RECEPTACLE OUTLET - WALL MOUNTED"),
    D("DUPLEX RECEPTACLE OUTLET - CEILING MOUNTED"),
    D("DUPLEX RECEPTACLE OUTLET - ABOVE BACKSPLASH"),
    V("CLOCK/INTERCOM SPEAKER COMBINATION"),
    V("COMMUNICATIONS DEVICE BOX"),
    V("COMMUNICATIONS DEVICE BOX - ABOVE BACKSPLASH"),
    V("WIRELESS ACCESS POINT"),
    V("HDMI/VGA INPUT MODULE - WALL MOUNTED"),
    V("PROJECTOR MOUNT - CEILING MOUNTED"),
    V("SPEAKER - RECESSED CEILING MOUNTED"),
    V("AUDIBLE/VISUAL ALARM - WALL MOUNTED"),
    D("JUNCTION BOX"),
    D("JUNCTION BOX - WALL MOUNTED"),
  ],
};
